### PR TITLE
Drop old python versions

### PR DESCRIPTION
**Pull request by hramezani**
- Drop support for Python < 3.7.
- Update syntax to Python3.7+
- Add badges to README.rst

### CODE REVIEW

**Comment by diazona** [comment]
Thanks for making the pull request! Is there a particular reason to drop support for these older Python versions, though? E.g. some new feature to be implemented that cannot be supported on Python versions less than 3.7?

Our approach so far has been to keep the package listed as compatible with older versions of Python when we can do so "for free". We only drop support for older versions when writing new code that requires it. I'd prefer to continue that.

**Comment by hramezani** [comment]
Your approach is OK. And you can continue to that.
IMHO, removing older python packages will push people to update their python version and you can use new python feature.  For example f-string.
BTW, feel free to close my PR if you think it's not necessary for now, or we may can use some part of the PR.

**Comment by diazona** [comment]
I understand what you're saying. But removing support for older Python versions in this package is probably not going to push anyone to update Python if it hasn't been done already. (In fact, I have one instance where making this change would cause me to stop using pytest-localserver entirely.) And there is no benefit in using new Python features just for the sake of using them. If it becomes helpful to use new features like f-strings and not worth the trouble to keep compatibility with older Python versions, I'd be happy to make these changes, but I don't think we're there yet.

So, yes, I would vote to just close this PR for now. Maybe in the future we can come back to it. But I won't do it just yet - I'll wait a few days in case either of the other maintainers want to chime in.

**Comment by hramezani** [comment]
Ok, thanks for explanation.
There are some changes in my PR which are related to python 2 and can be removed.
I will update my PR later

**Comment by hramezani** [comment]
I've created another PR (#36) to update the codebase syntax to Python 3.
We can close this one.

**Comment by diazona** [comment]
Since that and #38 got merged, I'll close this one now.

**Pull request closed without merging**
