### PR TITLE
Replace the _stop method, which was removed from aiosmtp 1.4.3, with the cancel_tasks method

### LINKED ISSUE #53: Bug: SMTP throws AttributeError on teardown
It seems smtp server isn't compatible anymore with the recent aiosmtpd vesrsion.
I'm getting the following error when teardown the smtp server. Before everything worked fine.
```
______________________________ ERROR at teardown of test_admin_permissions ______________________________

    @pytest.fixture(scope="session")
    def smtp_server():
        from pytest_localserver import smtp
    
        port = 3377
        server = smtp.Server(port=port)
        server.start()
        yield server
>       server.stop()

myapplication/tests/conftest.py:12: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <smtp.Server 127.0.0.1:3377>, timeout = None

    def stop(self, timeout=None):
        """
        Stops test server.
        :param timeout: When the timeout argument is present and not None, it
        should be a floating point number specifying a timeout for the
        operation in seconds (or fractions thereof).
        """
    
        # This mostly copies the implementation from Controller.stop(), with two
        # differences:
        # - It removes the assertion that the thread exists, allowing stop() to
        #   be called more than once safely
        # - It passes the timeout argument to Thread.join()
        if self.loop.is_running():
>           self.loop.call_soon_threadsafe(self._stop)
E           AttributeError: 'Server' object has no attribute '_stop'

__pypackages__/3.9/lib/pytest_localserver/smtp.py:133: AttributeError
```

### PR DESCRIPTION
**Pull request by henri-hulski**
Fixes #53 .

### CODE REVIEW

**Comment by diazona** [comment]
Thanks! So this looks fine; I'd just like to get the tests on Python <3.7 working before I merge. (Or, if it's too much effort, we can just drop compatibility with those old versions of Python.) I'll work on fixing the tests today or tomorrow.

**Comment by henri-hulski** [comment]
Ok. It seems quite difficult to maintain Python < 3.7. Github Actions doesn't seem to support it.
So I think it's fine to drop it.

**Comment by diazona** [comment]
It's not difficult, we just have to use an older version of Ubuntu. I made that fix in #56.

Anyway, it looks like these two pull requests need each other in order to get all the tests passing: yours fixes the tests on Python 3.7 and up, while mine fixes the tests on Python 3.6 and lower. So I'll probably just merge them both and hope that all the tests pass on master when it's done. But I would like to do it tomorrow because it's 2:30 AM for me right now :smile: (my personal rule of thumb: always wait a day before merging a PR, it helps catch stupid mistakes). Then perhaps I'll make a prerelease version early next week and you can test it, to be followed by a final release later in the week.

**Comment by diazona** [comment]
Hooray it works :smile:

**Comment by henri-hulski** [comment]
Great! 🎉
I will try it out.
If I gonna have any problems I tell you.
Actually already changed it in the venv and so far everything works fine.

**Pull request merged**
