### PR TITLE
Update package info

### PR DESCRIPTION
**Pull request by diazona**
This should be a start at updating the package metadata - mostly contributors and URL - to reflect the move to Github. I changed whatever I could think of, but if there's anything else that should be changed as part of this PR, happy to take contributions.

One item that needs to be resolved before merging: I believe the `maintainer` keyword to `setup()` only accepts one name and email address. @coordt should it be you or me? I don't particularly care, but it probably makes sense to be whichever one of us is going to be more active (if we have a sense of who that is).

### CODE REVIEW

**Comment by coordt** [comment]
I don't really care either. I'll follow your lead.

**Comment by diazona** [comment]
Cool, well... I dunno, I guess I'll keep it as is for now? Out of laziness if nothing else. We can always change later depending on who's taking a more active role at the time, or hopefully there will eventually be a way to list multiple maintainers in the package metadata. (I think I remember a PEP under consideration which would address that, not sure which one though)

I'd like to let this sit for a day or so to see if we think of anything else that should be added before merging.

**Comment by diazona** [comment]
Actually... @nicoddemus sorry to bother you again (I promise I won't do this often), but is there anything we should know about setting maintainers or other metadata for plugins like this one? Or is it just up to us to set the package metadata?

Also, are there specific review/approval requirements for PRs in plugin repositories under pytest-dev? I read [`pytest/CONTRIBUTING.rst`](https://github.com/pytest-dev/pytest/blob/main/CONTRIBUTING.rst) but it sounded like most of the requirements apply to pytest itself, not to plugin repositories. Just wanted to make sure we're not getting anything wrong here.

**Comment by nicoddemus** [comment]
> Actually... @nicoddemus sorry to bother you again (I promise I won't do this often)

No worries!

> but is there anything we should know about setting maintainers or other metadata for plugins like this one? Or is it just up to us to set the package metadata?

Not in particular, up to you folks.

Ahh but that reminds me, could you please add me and some other person from the core team as maintainer on PyPI? Please add me (`nicoddemus`) and perhaps @RonnyPfannschmidt (`ronny`)?

**Comment by diazona** [comment]
No objections, but I think @redtoad has to do that since I don't seem to have permission to add maintainers. I guess he added me and @coordt as maintainers rather than owners.

**Comment by nicoddemus** [comment]
In that case it would be great for @redtoad to add a few more owners to reduce the bus factor of the project.

**Comment by redtoad** [comment]
Done.

**Comment by redtoad** [comment]
I've just renamed README to README.rst which will make sure it is shown properly formatted. I hope you don't mind.

**Comment by diazona** [comment]
Oh no problem at all, thanks for that!

**Review by coordt — APPROVED** [review]

**Review by redtoad — APPROVED** [review]

**Pull request merged**
