### PR TITLE
Update changelog for the upcoming 0.6.0 release

### PR DESCRIPTION
**Pull request by diazona**
Everything listed under the 0.6.0 release milestone has been done (except this PR itself), so I figure it's time to release a new version. As usual, the April 27 date is just a placeholder; we should substitute in whatever we want to be the actual release date before merging this.

Anything else that should be added?

### CODE REVIEW

**Comment by redtoad** [comment]
Can you add a paragraph in the README (under "Development") how to do releases now?

**Comment by diazona** [comment]
> Can you add a paragraph in the README (under "Development") how to do releases now?

Sure thing. In another merge request, if that's okay?

**Comment by diazona** [comment]
I added that note in !33.

**Review by coordt — APPROVED** [review]

**Comment by diazona** [comment]
Thanks for the approval @coordt. I want to hold off on merging until @redtoad gets a chance to check #33, and then I'll merge that one, fix the date in this PR, merge this, and then make the release. (If that all sounds good)

**Pull request merged**
